### ISSUE TITLE
Webhook implementation of the folder preprocessor

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-v2#5]

**Comment by williamchong** [comment]
Some points to discuss
- What (or should any) kind of attributes are automatically added/calculated?
  - fileSize
  - mimeType
  - filehashes, sha256, md5, blake3
- Is expected format for json input same as `this one`(https://github.com/starlinglab/integrity-schema/blob/main/integrity-backend/input-browsertrix-examples/3e11cc57daf3bad8375935cad4878123acc8d769551ff90f1b1bb0dc597-meta-content.json) ?  That mean we would put most of the metadata field under `contentMetadata`
- Any expected field in response body?

Also points from https://github.com/starlinglab/integrity-v2/pull/1

- Using the gin framework seems unnecessary and the standard library [http](https://pkg.go.dev/net/http) could be used instead. I'd prefer to start simple and only add dependencies when needed.
- Instead of having its own go.mod and go.sum, the ingest folder should just be a submodule of integrity-v2, and share the dependencies. (We can go through this on a call if it's confusing)
- Similarly, you should move utils/cid.go into my util/ module
- The server should get its configuration from the config/ module in this repo
- I'm in favour of using the IPFS CLI over calculating it in Go but this will be debated later

**Comment by makew0rld** [comment]
> What (or should any) kind of attributes are automatically added/calculated? 

I think everything that can be calculated here should be, but that's still up for discussion.

> Is expected format for json input same as this one

No, I think we should ignore the old format. We should just use a simple JSON object/map, with key-value pairs. I wonder if we foresee any binary metadata being needed, in which case CBOR should be used instead. But probably JSON is fine.

> Any expected field in response body?

Empty response body should be fine on success (200). Having an error message in the response for error status codes would be helpful for debugging.

**Comment by williamchong** [comment]
Also not sure if we need to have a config about what attribute keys to be used(whitelist) or ignored(blacklist)
For example there was a `private` field in example json, which either should be encrypted or ignored. Likely not sure if there exists some `required` attribute that must exist in payload

**Comment by makew0rld** [comment]
I see. Yes you are right, we will need to separate things somewhat to allow for private (to be encrypted) attributes to be passed to the webhook. This will need to be documented. I still don't think any fields need to be required though. Just by convention our preprocessors will always provide certain fields.

Maybe the JSON can look like this simple format:

```json
{
    "my_field": 123,
    "my other data": "foo bar",
    "private": {
        "secret_data": "baz-123",
        "location": "Toronto"
    }
}
```

**Comment by makew0rld** [comment]
Further discussion tracked in #28
